### ISSUE TITLE
execution problem

### ISSUE THREAD

**Issue by anjonb16** [HenryDev/Voronoi-On-Gmaps#2]
how to run this file in windows system...
please guide step by step process to get the output.

**Comment by HenryDev** [comment]
1. Download Dart from https://www.dartlang.org/downloads/
2. Run main.dart from code editor, Dartium should open up and display maps with overlay

**Comment by HenryDev** [comment]
actually now that I look at it this project isn't complete. The working example in JS is here: https://gist.github.com/HenryDev/200528042af86e858146
